# -*- coding: utf-8 -*-
"""TP_BPA_GRUPO3_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15mnbankYJd4uPwcbCb1lLBG_GLArnwAC

# Trabajo Final BPA — Grupo 3
## Modelado Predictivo de Recaudación por Papeletas de Tránsito — SAT Lima
### Primer Trimestre 2026

| Campo | Detalle |
|---|---|
| **Integrantes** | Santiago Rojas · Abdiel Beraun · Victor Temoche · Orlando Mostacero · Manuel Chávez |
| **Curso** | Business Predictive Analytics — 1ASI0709 |
| **Dataset** | `Multas_transito_Pagadas_Ene_Mar_2026_I_TRIM_SAT.csv` |
| **Objetivo ML** | Regresión: estimar el `Monto total pagado` por papeleta |

---
> **Estructura del notebook:**
> 1. Collect Data
> 2. Calidad y Limpieza
> 3. EDA (Univariado, Bivariado, Multivariado)
> 4. Transformación de Datos + Pipeline
> 5. Modelado: Feature Selection + Modelos Base
> 6. Optimización de Hiperparámetros
> 7. Series Temporales — Recaudación Mensual
> 8. Resultados Finales e Insights

#Librerias para Despliegue
"""

"""## 0. Setup Global"""

# Commented out IPython magic to ensure Python compatibility.
# ── Librerías base ────────────────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
# %matplotlib inline

# Opciones de visualización
pd.options.display.float_format = '{:.3f}'.format
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_colwidth', 80)
sns.set_theme(style='whitegrid', palette='muted')

# ── Sklearn: preprocesamiento ──────────────────────────────────────
from sklearn.preprocessing import (
    RobustScaler,     # escalador robusto a outliers (usa mediana/IQR)
    OneHotEncoder,    # codificación nominal → columnas binarias
    OrdinalEncoder,   # codificación ordinal → entero con orden
    PowerTransformer, # Yeo-Johnson: reduce sesgo en variables numéricas
)
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# ── Sklearn: selección de features ────────────────────────────────
from sklearn.feature_selection import SelectFromModel, RFECV

# ── Sklearn: modelos ───────────────────────────────────────────────
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
)

# ── Sklearn: evaluación y optimización ────────────────────────────
from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    KFold,
    GridSearchCV,
    RandomizedSearchCV,
)
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score,
    mean_absolute_percentage_error,
)

import warnings
warnings.filterwarnings('ignore')

print('✓ Setup completo')

"""---
## Capítulo 2.1 — Collect Data

Cargamos el dataset oficial del SAT Lima: papeletas de tránsito **pagadas**
durante el primer trimestre de 2026 (Enero–Marzo).

**Fuente:** Plataforma Nacional de Datos Abiertos (PNDA) del Gobierno del Perú.
"""

# Cargar el CSV desde Google Drive
df = pd.read_csv('Multas_Pagadas.csv')

# Vista rápida del tamaño
print(f'Registros (filas)   : {df.shape[0]}')
print(f'Variables (columnas): {df.shape[1]}')

# Primeras filas para verificar la carga
df.head()

# Descripción de cada columna según dominio del SAT
columnas_descripcion = {
    'Código falta':          'Código de la infracción vial (ej. A01, B02)',
    'Descripción falta':     'Descripción textual de la infracción',
    'Tipo formato':          'Tipo de papeleta (Peatonal, Infracción, etc.)',
    'Nivel de gravedad':     'Gravedad: L=Leve, M=Moderada, G=Grave',
    'Año infracción':        'Año en que se cometió la infracción',
    'Año pago':              'Año en que se realizó el pago (2026 para todos)',
    'Mes pago':              'Mes de pago: 1=Enero, 2=Febrero, 3=Marzo',
    'Cant. multas con pagos':'Cantidad de multas que agrupa este registro',
    'Monto emitido':         'Monto original de la papeleta en soles',
    'Descuento':             'Descuento aplicado (por pronto pago, etc.)',
    'Importe pagado':        'Monto efectivamente pagado antes de ajustes',
    'Reincidencia pagada':   'Cargo adicional por reincidencia del infractor',
    'Monto total pagado':    'TARGET: monto final pagado al SAT'
}

desc_df = pd.DataFrame(list(columnas_descripcion.items()),
                        columns=['Columna', 'Descripción'])
desc_df

# Tipos de dato actuales — verificación inicial
print('Tipos de dato por columna:')
print(df.dtypes)

"""---
## Capítulo 2.2 — Calidad y Limpieza de Datos

Verificamos 5 dimensiones de calidad antes de cualquier transformación.

### Análisis 1 — Tipos de dato
"""

print('ANÁLISIS 1: TIPOS DE DATOS Y CONGRUENCIA')
print()

# Verificar que las columnas numéricas sean efectivamente numéricas
# y las categóricas sean strings
for col in df.columns:
    dtype = df[col].dtype
    n_unique = df[col].nunique()
    print(f'  {col:<30} dtype={str(dtype):<10} únicos={n_unique}')

print()
print('✓ Tipos de dato consistentes con el dominio del SAT')

"""### Análisis 2 — Valores nulos"""

print('ANÁLISIS 2: VALORES NULOS')
print()

nulos = pd.DataFrame({
    'Nulos':    df.isnull().sum(),
    '% Nulos': (df.isnull().sum() / len(df) * 100).round(2)
})
print(nulos)
print(f'\nTotal de valores nulos: {df.isnull().sum().sum()}')
print('✓ No se requiere acción — dataset sin nulos')

"""### Análisis 3 — Duplicados exactos"""

print('ANÁLISIS 3: DUPLICADOS EXACTOS')
print()

n_dup = df.duplicated().sum()
print(f'Filas completamente duplicadas: {n_dup}')
print('✓ No se requiere acción — sin duplicados')

"""### Análisis 4 — Columnas constantes (valor único)"""

print('ANÁLISIS 4: COLUMNAS CON UN ÚNICO VALOR (CONSTANTES)')
print()

# Si una columna tiene un único valor, no aporta poder discriminatorio al modelo
for c in df.columns.tolist():  # .tolist() para evitar modificar el iterador
    if df[c].nunique() == 1:
        valor = df[c].unique()[0]
        print(f"  Columna '{c}' → único valor: {valor}")
        print(f"  → No aporta información. Se elimina.")
        df.drop(columns=[c], inplace=True)

print(f'\nColumnas restantes: {df.shape[1]}')
print('✓ Columna "Año pago" eliminada (constante = 2026)')

"""### Análisis 5 — Espacios dobles en variables texto"""

print('ANÁLISIS 5: ESPACIOS ADICIONALES EN VARIABLES TEXTO')
print()

cat_cols = ['Código falta', 'Descripción falta', 'Tipo formato', 'Nivel de gravedad']

for c in cat_cols:
    doble_espacio = df[c].str.contains(r'  ', regex=False).sum()
    print(f'{c}: {doble_espacio} registros con doble espacio')

    if doble_espacio > 0:
        antes = df[c].nunique()
        # Corrección: eliminar espacios al inicio/fin y colapsar espacios internos
        df[c] = df[c].str.strip().str.replace(r' +', ' ', regex=True)
        despues = df[c].nunique()
        print(f'  Valores únicos antes  : {antes}')
        print(f'  Valores únicos después: {despues}')
        if antes != despues:
            print(f'  → Misma infracción registrada como dos descripciones distintas. Corregido.')

print()
print('✓ Corrección aplicada en "Descripción falta"')

"""### Resumen de limpieza"""

print('=' * 55)
print('  RESUMEN DE LIMPIEZA')
print('=' * 55)
print(f'  Registros originales      : 2225')
print(f'  Registros tras limpieza   : {len(df)}')
print(f'  Columnas originales        : 13')
print(f'  Columnas tras limpieza     : {len(df.columns)}')
print(f'  Valores nulos restantes    : {df.isnull().sum().sum()}')
print()
print('  Acciones aplicadas:')
print('  1. Tipos de dato → ✓ congruentes')
print('  2. Nulos → ninguno encontrado')
print('  3. Duplicados → ninguno encontrado')
print('  4. "Año pago" eliminada (valor constante = 2026)')
print('  5. "Descripción falta" corregida (espacios dobles)')
print('=' * 55)

df.head(3)

"""---
## Feature Engineering — Variables derivadas

Antes del EDA creamos variables que enriquecen el análisis y el modelo,
basadas en el dominio del negocio del SAT.
"""

# ── Variable: Años de rezago ──────────────────────────────────────
# Diferencia entre el año de pago (2026) y el año de la infracción
# Indica cuánto tiempo tardó el infractor en pagar su deuda
df['Años de rezago'] = 2026 - df['Año infracción']

# ── Variable: Es rezago ────────────────────────────────────────────
# True si la papeleta se pagó en un año distinto al de la infracción
# El 86% del dataset corresponde a deudas de años anteriores
df['Es rezago'] = df['Años de rezago'] > 0

# ── Variable: Descuento ────────────────────────────────────────────
# Descuento como monto absoluto (ya existe en el dataset)
# pero también calculamos indicador booleano y porcentaje

# ── Variable: Tiene descuento ─────────────────────────────────────
df['Tiene descuento'] = df['Descuento'] > 0

# ── Variable: Porcentaje de descuento ─────────────────────────────
# Descuento como % del monto emitido — útil para comparar entre montos distintos
df['Porcentaje descuento'] = (df['Descuento'] / df['Monto emitido'] * 100).round(2)

# ── Variable: Mes pago nombre ──────────────────────────────────────
# Etiqueta legible del mes (para gráficos y tablas)
meses = {1: 'Enero', 2: 'Febrero', 3: 'Marzo'}
df['Mes pago nombre'] = df['Mes pago'].map(meses)

print('Variables derivadas creadas:')
print('  • Años de rezago       — años entre infracción y pago')
print('  • Es rezago            — booleano: ¿es una deuda de año anterior?')
print('  • Tiene descuento      — booleano: ¿se aplicó algún descuento?')
print('  • Porcentaje descuento — descuento como % del monto emitido')
print('  • Mes pago nombre      — nombre del mes de pago')

df[['Año infracción','Años de rezago','Es rezago',
    'Descuento','Tiene descuento','Porcentaje descuento',
    'Mes pago nombre']].head()

"""---
## Capítulo 2.2 — EDA (Análisis Exploratorio)

El EDA tiene tres niveles: **univariado** (distribución de cada variable),
**bivariado** (relación entre pares), y **multivariado** (correlaciones globales).

### Variables numéricas y categóricas
"""

# Separar las variables según su tipo para análisis diferenciado
df_num = df.select_dtypes(include=['int64', 'float64']).copy()
df_cat = df.select_dtypes(include=['object', 'bool']).copy()

print(f'Variables numéricas  ({len(df_num.columns)}): {df_num.columns.tolist()}')
print(f'Variables categóricas ({len(df_cat.columns)}): {df_cat.columns.tolist()}')

"""### 4.1 Análisis Univariado — Estadísticos descriptivos"""

# Estadísticos descriptivos de las variables numéricas
df_num.describe().T

# Estadísticos adicionales: mediana, asimetría, curtosis, CV
resumen_num = pd.DataFrame({
    'Media':                   df_num.mean(),
    'Mediana':                 df_num.median(),
    'Desv. estándar':          df_num.std(),
    'Asimetría (skew)':        df_num.skew(),
    'Curtosis':                df_num.kurtosis(),
    'Coef. variación':        (df_num.std() / df_num.mean()).round(4),
})
resumen_num.round(3)

print('\nInterpretación:')
print('  skew > 1  → sesgo positivo fuerte (cola derecha larga)')
print('  CV alto   → alta variabilidad relativa respecto a la media')

"""### 4.2 Distribución de variables numéricas"""

cols_hist = ['Monto emitido', 'Descuento', 'Monto total pagado',
             'Años de rezago', 'Reincidencia pagada']

fig, axes = plt.subplots(2, 3, figsize=(16, 8))
axes = axes.flatten()

for i, col in enumerate(cols_hist):
    df[col].plot.hist(bins=30, ax=axes[i], color='steelblue', edgecolor='white')
    axes[i].axvline(df[col].mean(),   color='red',    linestyle='--', lw=1.2, label='Media')
    axes[i].axvline(df[col].median(), color='orange', linestyle='--', lw=1.2, label='Mediana')
    axes[i].set_title(f'{col}  (skew={df[col].skew():.2f})', fontsize=9)
    axes[i].legend(fontsize=7)
    axes[i].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))

axes[5].set_visible(False)
plt.suptitle('Distribucion de variables numericas (rojo=media, naranja=mediana)', fontsize=12)
plt.tight_layout()
plt.show()

"""### 4.3 Nivel de gravedad"""

# Frecuencia y gráfico del nivel de gravedad
print(df['Nivel de gravedad'].value_counts())
print()

orden = ['L', 'M', 'G']
sns.countplot(data=df, x='Nivel de gravedad', order=orden,
              hue='Nivel de gravedad', legend=False, palette='viridis')
plt.title('Frecuencia de multas por nivel de gravedad (L < M < G)')
plt.xlabel('Nivel de gravedad')
plt.ylabel('Cantidad de multas')
plt.show()

"""### 4.4 Tipo de formato"""

print(df['Tipo formato'].value_counts())
print()

df['Tipo formato'].value_counts().plot(
    kind='barh', color='steelblue', edgecolor='white')
plt.title('Frecuencia de multas por tipo de formato')
plt.xlabel('Cantidad de multas')
plt.show()

"""### 4.5 Distribución temporal — mes de pago"""

conteo_mes = df['Mes pago nombre'].value_counts().reindex(['Enero','Febrero','Marzo'])
print(conteo_mes)
print()

conteo_mes.plot(kind='bar', color='steelblue', edgecolor='white')
plt.title('Cantidad de multas pagadas por mes')
plt.xlabel('Mes de pago')
plt.ylabel('Cantidad de multas')
plt.xticks(rotation=0)
plt.show()

"""### 4.6 Rezago y descuento"""

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

# Distribución: ¿es rezago?
df['Es rezago'].value_counts().plot(kind='bar', ax=axes[0], color='steelblue', edgecolor='white')
axes[0].set_title('Papeletas con y sin rezago')
axes[0].set_xlabel('¿Es rezago?')
axes[0].tick_params(axis='x', rotation=0)

# Histograma: años de rezago
df['Años de rezago'].plot.hist(bins=20, ax=axes[1], color='steelblue', edgecolor='white')
axes[1].set_title('Distribución de años de rezago')
axes[1].set_xlabel('Años de rezago')

# Distribución: ¿tiene descuento?
df['Tiene descuento'].value_counts().plot(kind='bar', ax=axes[2], color='salmon', edgecolor='white')
axes[2].set_title('Papeletas con y sin descuento')
axes[2].set_xlabel('¿Tiene descuento?')
axes[2].tick_params(axis='x', rotation=0)

plt.tight_layout()
plt.show()

print(f"Papeletas con rezago   : {df['Es rezago'].sum()} ({df['Es rezago'].mean():.1%})")
print(f"Papeletas con descuento: {df['Tiene descuento'].sum()} ({df['Tiene descuento'].mean():.1%})")
print(f"Años de rezago promedio: {df['Años de rezago'].mean():.2f}")

"""### 4.7 Análisis Bivariado — Recaudación por variables clave"""

fig, axes = plt.subplots(1, 3, figsize=(17, 5))

# ── Recaudación total por mes ──────────────────────────────────────
rec_mes = df.groupby('Mes pago nombre')['Monto total pagado'].sum().reindex(
    ['Enero','Febrero','Marzo'])

rec_mes.plot(kind='bar', ax=axes[0], color='steelblue', edgecolor='white')
axes[0].set_title('Recaudación total por mes')
axes[0].set_xlabel('Mes')
axes[0].set_ylabel('Monto (S/)')
axes[0].tick_params(axis='x', rotation=0)
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'S/{x/1e6:.1f}M'))
for bar in axes[0].patches:
    axes[0].text(bar.get_x()+bar.get_width()/2, bar.get_height()*1.01,
                 f'S/{bar.get_height():,.0f}', ha='center', fontsize=7)

# ── Recaudación total por nivel de gravedad ────────────────────────
rec_grav = df.groupby('Nivel de gravedad')['Monto total pagado'].sum().sort_values(ascending=False)

rec_grav.plot(kind='bar', ax=axes[1], color='salmon', edgecolor='white')
axes[1].set_title('Recaudación por nivel de gravedad')
axes[1].set_xlabel('Gravedad')
axes[1].set_ylabel('Monto (S/)')
axes[1].tick_params(axis='x', rotation=0)
axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'S/{x/1e6:.1f}M'))

# ── Recaudación por año de infracción ─────────────────────────────
rec_anio = df.groupby('Año infracción')['Monto total pagado'].sum().sort_index()

rec_anio.plot(kind='bar', ax=axes[2], color='teal', edgecolor='white')
axes[2].set_title('Recaudación por año de infracción')
axes[2].set_xlabel('Año infracción')
axes[2].set_ylabel('Monto (S/)')
axes[2].tick_params(axis='x', rotation=45)
axes[2].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'S/{x/1e6:.1f}M'))

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Boxplot: monto pagado según descuento
sns.boxplot(data=df, x='Tiene descuento', y='Monto total pagado', ax=axes[0])
axes[0].set_title('Monto pagado según aplicación de descuento')
axes[0].set_xlabel('¿Tiene descuento?')
axes[0].set_ylabel('Monto total pagado (S/)')
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))

# Boxplot: monto pagado según rezago
sns.boxplot(data=df, x='Es rezago', y='Monto total pagado', ax=axes[1])
axes[1].set_title('Monto pagado según existencia de rezago')
axes[1].set_xlabel('¿Es rezago?')
axes[1].set_ylabel('Monto total pagado (S/)')
axes[1].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))

plt.tight_layout()
plt.show()

# Scatter: monto emitido vs monto total pagado
plt.figure(figsize=(9, 5))
sns.scatterplot(data=df, x='Monto emitido', y='Monto total pagado', alpha=0.4, s=20)
plt.title('Relación entre monto emitido y monto total pagado')
plt.xlabel('Monto emitido (S/)')
plt.ylabel('Monto total pagado (S/)')
plt.gca().xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))
plt.gca().yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))
plt.tight_layout()
plt.show()

r = df['Monto emitido'].corr(df['Monto total pagado'])
print(f'Correlación Pearson entre monto emitido y monto total pagado: r = {r:.4f}')

# Top 10 códigos de falta más frecuentes con descripción
top10 = (df.groupby(['Código falta','Descripción falta'])
           .size().reset_index(name='Cantidad')
           .sort_values('Cantidad', ascending=False)
           .head(10))
top10

# Gráfico
top10.sort_values('Cantidad').plot(
    kind='barh', x='Código falta', y='Cantidad',
    color='steelblue', edgecolor='white', legend=False, figsize=(9, 5))
plt.title('Top 10 códigos de falta más frecuentes')
plt.xlabel('Cantidad de multas')
plt.tight_layout()
plt.show()

"""### 4.8 Análisis Multivariado — Matriz de correlación"""

# Correlación entre todas las variables numéricas (incluidas las derivadas)
cols_corr = ['Monto emitido','Descuento','Importe pagado','Reincidencia pagada',
             'Monto total pagado','Años de rezago','Porcentaje descuento',
             'Cant. multas con pagos']

corr = df[cols_corr].corr()

plt.figure(figsize=(11, 8))
sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, vmin=-1, vmax=1, linewidths=0.5, annot_kws={'size': 9}, square=True)
plt.title('Matriz de Correlación — Variables Numéricas', fontsize=13)
plt.tight_layout()
plt.show()

"""### 4.9 Tabla de recaudación por nivel de gravedad"""

tabla_grav = df.groupby('Nivel de gravedad').agg(
    Cantidad=('Monto total pagado', 'count'),
    Total_S=('Monto total pagado', 'sum'),
    Promedio_S=('Monto total pagado', 'mean'),
    Mediana_S=('Monto total pagado', 'median'),
    Rezago_promedio=('Años de rezago', 'mean')
).sort_values('Total_S', ascending=False)

tabla_grav.round(2)

"""---
## Capítulo 2.3 — Transformación de Datos e Implementación de Pipeline

### Análisis de Selección de Variables

Antes de construir el pipeline, analizamos outliers y el tipo de cada variable
para elegir la transformación adecuada.

#### Variables Numéricas — Outliers
"""

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

cols_box = ['Monto emitido', 'Años de rezago', 'Descuento']
colores   = ['steelblue', 'salmon', 'teal']

for i, (col, color) in enumerate(zip(cols_box, colores)):
    sns.boxplot(x=df[col], ax=axes[i], color=color)
    axes[i].set_title(f'Boxplot: {col}')
    axes[i].xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))

plt.suptitle('Distribución de variables numéricas — detección de outliers', fontsize=11)
plt.tight_layout()
plt.show()

print('Observación: "Monto emitido" y "Descuento" presentan outliers significativos.')
print('→ Se justifica usar RobustScaler (mediana/IQR) en vez de StandardScaler.')

"""#### Variables Nominales — Cardinalidad"""

# Verificar el número de categorías únicas por variable nominal
print('Categorías en Tipo formato:', df['Tipo formato'].unique())
print('Categorías en Mes de pago :', df['Mes pago nombre'].unique())
print()

print('Frecuencia por Tipo formato:')
print(df['Tipo formato'].value_counts())
print()
print('→ Cardinalidad baja (< 10 categorías) → OneHotEncoder es apropiado')

"""#### Variable Ordinal — Jerarquía"""

# Visualizar que la distribución respeta la jerarquía L < M < G
orden_logico = ['L', 'M', 'G']
sns.countplot(data=df, x='Nivel de gravedad', order=orden_logico,
              hue='Nivel de gravedad', legend=False, palette='viridis')
plt.title('Frecuencia por Nivel de Gravedad (L < M < G) - L=Leve, M=Moderada, G=Grave')
plt.show()
print('→ Existe un orden natural → OrdinalEncoder con categorías [L, M, G]')

"""### Construcción del Pipeline"""

# ── Sub-pipeline numérico ──────────────────────────────────────────
# RobustScaler: usa mediana/IQR → robusto a outliers detectados en los boxplots
pipe_num = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),  # mediana: robusta a outliers
    ('scaler',  RobustScaler())                     # escalar con mediana/IQR
])

# ── Sub-pipeline nominal ───────────────────────────────────────────
# OneHotEncoder: crea columna 0/1 por cada categoría
# drop='first' → elimina primera categoría para evitar multicolinealidad
pipe_nom = Pipeline(steps=[
    ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False))
])

# ── Sub-pipeline ordinal ───────────────────────────────────────────
# OrdinalEncoder: asigna enteros respetando el orden L=0, M=1, G=2
orden_gravedad = [['L', 'M', 'G']]
pipe_ord = Pipeline(steps=[
    ('ordinal', OrdinalEncoder(categories=orden_gravedad,
                               handle_unknown='use_encoded_value',
                               unknown_value=-1))
])

print('Sub-pipelines definidos:')
print('  num → RobustScaler  (por outliers en montos y rezago)')
print('  nom → OneHotEncoder (Tipo formato, Mes pago nombre)')
print('  ord → OrdinalEncoder [L=0, M=1, G=2]')

# Definir columnas por tipo de transformación
cols_num = ['Monto emitido', 'Años de rezago', 'Descuento',
            'Reincidencia pagada', 'Cant. multas con pagos']
cols_nom = ['Tipo formato', 'Mes pago nombre']
cols_ord = ['Nivel de gravedad']

# TARGET: Monto total pagado (variable de regresión)
TARGET = 'Monto total pagado'

# ColumnTransformer: aplica cada sub-pipeline a sus columnas
# remainder='drop' → columnas no listadas (ej. IDs, textos) se descartan
preprocesador = ColumnTransformer(
    transformers=[
        ('num', pipe_num, cols_num),
        ('nom', pipe_nom, cols_nom),
        ('ord', pipe_ord, cols_ord),
    ],
    remainder='drop'
)

print('ColumnTransformer ensamblado:')
print(f'  Numéricas ({len(cols_num)}) : {cols_num}')
print(f'  Nominales ({len(cols_nom)}) : {cols_nom}')
print(f'  Ordinales ({len(cols_ord)}) : {cols_ord}')

# Separar features (X) y target (y)
X = df[cols_num + cols_nom + cols_ord].copy()
y = df[TARGET].copy()

# Train / Test split — 80/20 con semilla fija para reproducibilidad
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

print(f'Train: {X_train.shape[0]} filas ({X_train.shape[0]/len(X):.0%})')
print(f'Test : {X_test.shape[0]} filas  ({X_test.shape[0]/len(X):.0%})')
print(f'Target — media train: S/{y_train.mean():,.2f}  |  test: S/{y_test.mean():,.2f}')

"""---
## Capítulo 4.1 — Modelización: Feature Selection

Antes de comparar modelos, identificamos cuáles variables tienen mayor
poder predictivo para el `Monto total pagado`.
"""

# Primero ajustamos el preprocesador para obtener la matriz transformada
# (esto es solo para el análisis de importancia — el modelo final va en Pipeline)
X_train_tr = preprocesador.fit_transform(X_train, y_train)
X_test_tr  = preprocesador.transform(X_test)

# Nombre de las columnas después del encoding
names_num = cols_num
names_nom = preprocesador.named_transformers_['nom']['onehot']                         .get_feature_names_out(cols_nom).tolist()
names_ord = cols_ord
feature_names = names_num + names_nom + names_ord

print(f'Features después del preprocesamiento: {len(feature_names)}')
print(feature_names)

from sklearn.feature_selection import SelectFromModel

# Entrenar un Random Forest auxiliar para obtener feature importances
rf_selector = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_selector.fit(X_train_tr, y_train)

# Calcular importancias
importancias = pd.DataFrame({
    'Variable':    feature_names,
    'Importancia': rf_selector.feature_importances_
}).sort_values('Importancia', ascending=False)

print(f'Importancia promedio: {rf_selector.feature_importances_.mean():.4f}')
print()
print('Top features:')
importancias

# Visualizar importancias
plt.figure(figsize=(9, 5))
sns.barplot(data=importancias, x='Importancia', y='Variable', palette='viridis')
plt.title('Feature Importance — Random Forest (auxiliar)')
plt.tight_layout()
plt.show()

print('Observación: "Monto emitido" domina claramente la importancia.')
print('Esto es coherente con la correlación r > 0.98 detectada en el EDA.')

# SelectFromModel: seleccionar features con importancia > umbral (media)
selector_sfm = SelectFromModel(rf_selector, prefit=True, threshold='mean')
features_seleccionadas = np.array(feature_names)[selector_sfm.get_support()]

print(f'Features seleccionadas por SelectFromModel: {len(features_seleccionadas)}')
print(features_seleccionadas)

# Cross-validation con TODAS las features (referencia)
kf = KFold(n_splits=5, shuffle=True, random_state=42)

pipe_rf_todas = Pipeline([
    ('prep',  preprocesador),
    ('model', RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1))
])
cv_todas = cross_val_score(pipe_rf_todas, X_train, y_train, cv=kf, scoring='r2')
print(f'\nR² CV con TODAS las features    : {cv_todas.mean():.4f} ± {cv_todas.std():.4f}')

"""---
## Capítulo 4.1 — Modelización: Comparación de Modelos Base

Comparamos 5 modelos con hiperparámetros por defecto usando el mismo Pipeline
para garantizar condiciones justas de comparación.
"""

# Definir todos los modelos dentro de su Pipeline
# Todos usan el mismo preprocesador para comparación justa
modelos = {
    'Regresión Lineal':    LinearRegression(),
    'Ridge':               Ridge(alpha=1.0),
    'Lasso':               Lasso(alpha=1.0, max_iter=5000),
    'Árbol Decisión':      DecisionTreeRegressor(max_depth=6, random_state=42),
    'Random Forest':       RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    'Gradient Boosting':   GradientBoostingRegressor(n_estimators=100, random_state=42),
}

pipelines = {
    nombre: Pipeline([('prep', preprocesador), ('model', modelo)])
    for nombre, modelo in modelos.items()
}

print(f'Modelos a comparar: {len(pipelines)}')
for n in pipelines:
    print(f'  • {n}')

# Cross-Validation 5-fold con R² y RMSE
print('Cross-Validation (5-fold) sobre Train Set...\n')

cv_resultados = []
for nombre, pipe in pipelines.items():
    # R²: mayor es mejor — proporción de varianza explicada
    r2_scores   = cross_val_score(pipe, X_train, y_train, cv=kf, scoring='r2')
    # RMSE: menor es mejor — error en soles
    rmse_scores = np.sqrt(-cross_val_score(pipe, X_train, y_train, cv=kf,
                                            scoring='neg_mean_squared_error'))
    # MAE: menor es mejor — error absoluto medio
    mae_scores  = -cross_val_score(pipe, X_train, y_train, cv=kf,
                                    scoring='neg_mean_absolute_error')
    cv_resultados.append({
        'Modelo':      nombre,
        'R² medio':    round(r2_scores.mean(), 4),
        'R² std':      round(r2_scores.std(),  4),
        'RMSE medio':  round(rmse_scores.mean(), 2),
        'MAE medio':   round(mae_scores.mean(), 2),
    })
    print(f'  {nombre:<22} R²={r2_scores.mean():.4f} ± {r2_scores.std():.4f}   '
          f'RMSE={rmse_scores.mean():.2f}')

cv_df = pd.DataFrame(cv_resultados).sort_values('R² medio', ascending=False)
print()
cv_df

# Gráfico comparativo de R² por modelo
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
colors = plt.cm.Set2(np.linspace(0, 1, len(cv_df)))

# R² con barras de error
axes[0].barh(cv_df['Modelo'], cv_df['R² medio'],
             xerr=cv_df['R² std'], color=colors, edgecolor='white',
             capsize=4, height=0.55)
axes[0].set_title('R2 medio - CV 5-fold (mayor = mejor)', fontsize=11)
axes[0].set_xlabel('R²')
axes[0].axvline(0, color='black', lw=0.8)

# RMSE
axes[1].barh(cv_df['Modelo'], cv_df['RMSE medio'],
             color=colors, edgecolor='white', height=0.55)
axes[1].set_title('RMSE medio - CV 5-fold (menor = mejor, en S/)', fontsize=11)
axes[1].set_xlabel('RMSE (S/)')

plt.suptitle('Comparación de Modelos Base — Cross-Validation sobre Train Set', fontsize=12)
plt.tight_layout()
plt.show()

"""---
## Capítulo 4.2 — Optimización de Hiperparámetros

Optimizamos los dos mejores modelos del paso anterior con `GridSearchCV`
(búsqueda exhaustiva) y `RandomizedSearchCV` (búsqueda aleatoria).

| Método | Cómo funciona | Cuándo usarlo |
|---|---|---|
| **GridSearchCV** | Prueba TODAS las combinaciones | Grid pequeño, exhaustivo |
| **RandomizedSearchCV** | Prueba N combinaciones aleatorias | Grid grande, necesitas rapidez |

### Optimización — Random Forest (GridSearchCV)
"""

# Definir Pipeline de Random Forest para optimización
pipe_rf_opt = Pipeline([
    ('prep',  preprocesador),
    ('model', RandomForestRegressor(random_state=42, n_jobs=-1))
])

# Grilla de hiperparámetros
# Nota: los nombres llevan prefijo 'model__' porque están dentro del Pipeline
param_grid_rf = {
    'model__n_estimators': [100, 200, 300],
    'model__max_depth':    [5, 10, 15, None],
    'model__min_samples_split': [2, 5],
    'model__min_samples_leaf':  [1, 2],
}

# Total de combinaciones
total_rf = 1
for v in param_grid_rf.values():
    total_rf *= len(v)
print(f'Total de combinaciones: {total_rf}  |  Con 5-fold CV: {total_rf * 5} entrenamientos')

grid_rf = GridSearchCV(
    pipe_rf_opt, param_grid=param_grid_rf,
    scoring='r2', cv=kf, n_jobs=-1, verbose=1
)
grid_rf.fit(X_train, y_train)

print(f'\nMejores hiperparámetros (Random Forest):')
for param, val in grid_rf.best_params_.items():
    print(f'  {param}: {val}')
print(f'\nMejor R² (CV): {grid_rf.best_score_:.4f}')

"""### Optimización — Gradient Boosting (RandomizedSearchCV)"""

from scipy.stats import randint, uniform

pipe_gb_opt = Pipeline([
    ('prep',  preprocesador),
    ('model', GradientBoostingRegressor(random_state=42))
])

# Espacio de búsqueda más amplio — RandomizedSearch explora N combinaciones aleatorias
param_random_gb = {
    'model__n_estimators':  [100, 200, 300, 500],
    'model__max_depth':     [3, 4, 5, 6],
    'model__learning_rate': [0.01, 0.05, 0.1, 0.2],
    'model__subsample':     [0.8, 0.9, 1.0],
    'model__min_samples_leaf': [1, 2, 4],
}

# Probar 30 combinaciones aleatorias del espacio
random_gb = RandomizedSearchCV(
    pipe_gb_opt, param_distributions=param_random_gb,
    n_iter=30, scoring='r2', cv=kf,
    n_jobs=-1, verbose=1, random_state=42
)
random_gb.fit(X_train, y_train)

print(f'\nMejores hiperparámetros (Gradient Boosting):')
for param, val in random_gb.best_params_.items():
    print(f'  {param}: {val}')
print(f'\nMejor R² (CV): {random_gb.best_score_:.4f}')

"""### Tabla comparativa — base vs optimizados"""

# Recopilar todos los scores de CV
auc_rf_grid,   std_rf_grid   = grid_rf.best_score_,   grid_rf.cv_results_['std_test_score'][grid_rf.best_index_]
auc_gb_random, std_gb_random = random_gb.best_score_, random_gb.cv_results_['std_test_score'][random_gb.best_index_]

comparacion = pd.DataFrame({
    'Modelo': [
        'Regresión Lineal (base)',
        'Random Forest (base)',
        'Gradient Boosting (base)',
        'Random Forest + GridSearch',
        'Gradient Boosting + RandomSearch',
    ],
    'R² (CV)': [
        cv_df.loc[cv_df['Modelo']=='Regresión Lineal', 'R² medio'].values[0],
        cv_df.loc[cv_df['Modelo']=='Random Forest',    'R² medio'].values[0],
        cv_df.loc[cv_df['Modelo']=='Gradient Boosting','R² medio'].values[0],
        auc_rf_grid,
        auc_gb_random,
    ],
    'Std': [
        cv_df.loc[cv_df['Modelo']=='Regresión Lineal', 'R² std'].values[0],
        cv_df.loc[cv_df['Modelo']=='Random Forest',    'R² std'].values[0],
        cv_df.loc[cv_df['Modelo']=='Gradient Boosting','R² std'].values[0],
        std_rf_grid,
        std_gb_random,
    ]
}).sort_values('R² (CV)', ascending=False).reset_index(drop=True)

print('COMPARACIÓN: Modelos Base vs Optimizados')
print('=' * 55)
display(comparacion.round(4))

"""---
## Capítulo 5.1 — Evaluación Final en Test

Seleccionamos el mejor modelo de CV y lo evaluamos en el **test set**
(datos que el modelo nunca vio durante el entrenamiento ni la optimización).
"""

# Elegir el modelo con mayor R² en CV
# (ajusta esta línea según los resultados de tu grid)
mejor_modelo = grid_rf.best_estimator_   # ← si RF gana; cambiar a random_gb.best_estimator_ si GB gana

# Predecir en test
y_pred  = mejor_modelo.predict(X_test)

# Métricas finales
r2   = r2_score(y_test, y_pred)
mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mape = mean_absolute_percentage_error(y_test, y_pred) * 100

print('=== MODELO FINAL — Evaluación en TEST ===')
print(f'R²    : {r2:.4f}  (proporción de varianza explicada)')
print(f'MAE   : S/{mae:,.2f}  (error absoluto medio en soles)')
print(f'RMSE  : S/{rmse:,.2f}  (error cuadrático medio)')
print(f'MAPE  : {mape:.2f}%  (error porcentual promedio)')

# Diagnóstico visual del modelo final
residuos = y_test.values - y_pred

fig, axes = plt.subplots(1, 3, figsize=(17, 5))

# 1. Real vs Predicho
axes[0].scatter(y_test, y_pred, alpha=0.4, s=15, color='steelblue')
lim = [min(y_test.min(), y_pred.min()), max(y_test.max(), y_pred.max())]
axes[0].plot(lim, lim, 'r--', lw=1.5, label='Predicción perfecta')
axes[0].set_title('Real vs Predicho')
axes[0].set_xlabel('Monto real (S/)')
axes[0].set_ylabel('Monto predicho (S/)')
axes[0].text(0.05, 0.90, f'R²={r2:.4f}', transform=axes[0].transAxes,
             fontsize=11, color='red', fontweight='bold')
axes[0].legend(fontsize=9)

# 2. Residuos vs Predicho
axes[1].scatter(y_pred, residuos, alpha=0.4, s=14, color='coral')
axes[1].axhline(0, color='black', lw=1.5, ls='--')
axes[1].set_title('Residuos vs Predicho (ideal: puntos aleatorios alrededor de 0)')
axes[1].set_xlabel('Monto predicho (S/)')
axes[1].set_ylabel('Residuo (real − predicho)')

# 3. Distribución de residuos
axes[2].hist(residuos, bins=35, color='teal', edgecolor='white')
axes[2].axvline(0, color='red', ls='--', lw=1.5)
axes[2].axvline(residuos.mean(), color='orange', ls='--', lw=1.5,
                label=f'Media={residuos.mean():.2f}')
axes[2].set_title('Distribucion de Residuos (ideal: campana centrada en 0)')
axes[2].legend(fontsize=9)

plt.suptitle('Diagnóstico del Modelo Final — Test Set', fontsize=12, y=1.01)
plt.tight_layout()
plt.show()

# Comparación final: CV vs Test
print('=== Comparación CV vs Test ===')
print(f'R² CV (promedio) : {grid_rf.best_score_:.4f}  ±  {std_rf_grid:.4f}')
print(f'R² Test          : {r2:.4f}')
dif = abs(grid_rf.best_score_ - r2)
if dif < 0.05:
    print('✓ Diferencia pequeña → el modelo generaliza bien')
else:
    print('⚠ Diferencia considerable → revisar posible overfitting')

"""---
## Capítulo 7 — Series Temporales: Recaudación por Semana

Complementamos el modelo de regresión con un análisis de serie temporal
de la recaudación semanal para identificar tendencia, estacionalidad
y proyectar la recaudación futura.
"""

# Construir serie temporal: recaudación por semana de pago
# Usamos el mes y una aproximación de semana (no tenemos fecha exacta)
# Agrupamos por (Mes, franja de 5 días) como proxy de semana

# Primero agrupamos por mes de pago para la serie mensual
serie_mensual = df.groupby('Mes pago nombre')['Monto total pagado'].sum().reindex(
    ['Enero', 'Febrero', 'Marzo'])
serie_mensual.index = pd.to_datetime(['2026-01-31', '2026-02-28', '2026-03-31'])

print('Recaudación mensual:')
print(serie_mensual)

# Visualizar la serie mensual de recaudación
fig, ax = plt.subplots(figsize=(10, 4))
ax.plot(serie_mensual.index, serie_mensual.values, 'o-',
        color='steelblue', linewidth=2, markersize=8)
ax.fill_between(serie_mensual.index, serie_mensual.values, alpha=0.15, color='steelblue')

for x, y in zip(serie_mensual.index, serie_mensual.values):
    ax.annotate(f'S/{y/1e6:.2f}M', (x, y),
                textcoords='offset points', xytext=(0, 10), ha='center', fontsize=10)

ax.set_title('Recaudacion mensual por papeletas de transito Q1 2026 (SAT Lima)', fontsize=12)
ax.set_ylabel('Monto total (S/)')
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'S/{x/1e6:.1f}M'))
ax.grid(True, alpha=0.4)
plt.tight_layout()
plt.show()

# Proyección simple por suavización exponencial
# Con solo 3 puntos no podemos descomponer estacionalidad,
# pero sí podemos hacer una proyección lineal y de suavización

from statsmodels.tsa.holtwinters import ExponentialSmoothing

# Proyección con suavización exponencial simple (sin estacionalidad, solo tendencia)
# Necesitamos más datos para ARIMA/ETS completo, por lo que usamos tendencia lineal
meses = np.arange(1, 4)
valores = serie_mensual.values

# Ajuste lineal
coef = np.polyfit(meses, valores, 1)
linea = np.poly1d(coef)

# Proyectar Abril y Mayo
meses_ext  = np.arange(1, 6)
proyeccion = linea(meses_ext)
fechas_ext = pd.to_datetime(['2026-01-31','2026-02-28','2026-03-31',
                              '2026-04-30','2026-05-31'])

fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(fechas_ext[:3], valores, 'o-', color='steelblue', lw=2, ms=8, label='Observado')
ax.plot(fechas_ext[2:], proyeccion[2:], 's--', color='salmon', lw=2, ms=8, label='Proyección lineal')

ax.set_title('Recaudacion Q1 2026 + Proyeccion Abr-May (tendencia lineal)', fontsize=11)
ax.set_ylabel('Monto (S/)')
ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'S/{x/1e6:.2f}M'))
ax.legend()
ax.grid(True, alpha=0.4)
plt.tight_layout()
plt.show()

print('Proyección mensual (tendencia lineal):')
nombres_meses = ['Enero','Febrero','Marzo','Abril (proy.)','Mayo (proy.)']
for nombre, val in zip(nombres_meses, proyeccion):
    print(f'  {nombre:<18}: S/{val:,.0f}')

print()
print('Nota: Con solo 3 meses de datos la proyección es indicativa.')
print('Para un modelo ETS/ARIMA robusto se recomienda al menos 24 meses de historia.')

# Serie por año de infracción: ¿cómo fluye la cartera pesada?
# Esto muestra el "rezago temporal" de la cartera del SAT

serie_anio = df.groupby('Año infracción').agg(
    Cantidad=('Monto total pagado', 'count'),
    Recaudacion=('Monto total pagado', 'sum'),
    Rezago_promedio=('Años de rezago', 'mean')
).sort_index()

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Recaudación por año de infracción
serie_anio['Recaudacion'].plot(ax=axes[0], kind='bar', color='steelblue', edgecolor='white')
axes[0].set_title('Recaudacion Q1 2026 segun anio de infraccion (antiguedad de deuda)')
axes[0].set_xlabel('Año de infracción')
axes[0].set_ylabel('Monto recaudado (S/)')
axes[0].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'S/{x/1e6:.1f}M'))
axes[0].tick_params(axis='x', rotation=45)

# Rezago promedio por año de infracción
axes[1].plot(serie_anio.index, serie_anio['Rezago_promedio'], 'o-',
             color='salmon', lw=2, ms=7)
axes[1].set_title('Anios de rezago promedio por anio de infraccion')
axes[1].set_xlabel('Año de infracción')
axes[1].set_ylabel('Rezago promedio (años)')
axes[1].grid(True, alpha=0.4)

plt.tight_layout()
plt.show()

"""---
## Capítulo 3.1 / 5.1 / 6 — Insights, Resultados y Conclusiones

### Insights del EDA

1. **El rezago es estructural:** el 86% de las papeletas pagadas en Q1 2026 corresponden
   a deudas de años anteriores, con un rezago promedio de ~5.8 años. Esto confirma
   que el SAT depende críticamente de la recuperación de cartera antigua ("cartera pesada"),
   no solo de infracciones del año vigente.

2. **El descuento como palanca de recaudación:** las papeletas con descuento tienen
   montos totales pagados más bajos pero mayor volumen de pago — sugiere que las
   campañas de descuento por pronto pago efectivamente movilizan el pago de deudas
   antiguas.

3. **Las multas Graves concentran la mayor recaudación:** aunque son menos en cantidad,
   los niveles G (Grave) generan la mayor proporción del ingreso total del SAT.
   Priorizar la cobranza de estas papeletas tiene el mayor impacto en la caja.

4. **Estacionalidad mensual visible:** Enero concentra la mayor recaudación del
   trimestre, posiblemente relacionado con las campañas de amnistía de inicio de año
   y el efecto gratificación/CTS de diciembre previo.

5. **El monto emitido es el predictor dominante:** con r > 0.95 respecto al
   monto total pagado, el monto original de la papeleta es la variable más importante.
   Las demás variables (rezago, gravedad, formato) actúan como moduladores del precio.

---
### Conclusiones Técnicas (Capítulo 6.1)

- El modelo de **Random Forest optimizado** con GridSearchCV logra el mejor
  balance entre R² alto y baja varianza en Cross-Validation, siendo la
  opción más confiable para proyectar el monto de recaudación.

- Los modelos de **regresión lineal** (Ridge/Lasso) obtienen R² elevados
  porque la relación entre monto emitido y monto pagado es casi lineal.
  Sin embargo, los modelos de ensamble capturan mejor las interacciones
  no lineales entre rezago, gravedad y formato.

- La **transformación con RobustScaler** fue crítica: los outliers en
  `Monto emitido` distorsionarían el StandardScaler, y el RobustScaler
  mitiga este efecto usando la mediana e IQR.

---
### Recomendaciones (Capítulo 6.2)

1. **Ampliar la serie temporal:** con solo Q1 2026 no es posible modelar
   estacionalidad anual. Se recomienda incorporar los 4 trimestres de 2024 y 2025
   para construir un modelo ETS/ARIMA robusto de proyección mensual.

2. **Segmentar la cobranza:** dado el dominio de la gravedad G en la recaudación,
   diseñar campañas de cobranza diferenciadas por gravedad y por antigüedad
   del rezago (priorizar 1-5 años donde la probabilidad de pago es mayor).

3. **Modelo complementario de clasificación:** aunque el dataset actual solo
   tiene papeletas pagadas, cruzarlo con el universo total de papeletas emitidas
   permitiría construir un modelo de clasificación para predecir la probabilidad
   de pago, habilitando cobranza predictiva.

---
### Aportes (Capítulo 6.3)

- Propuesta de pipeline de ML reproducible y explicable para el SAT Lima
- Feature Engineering de variables de dominio (rezago, descuento, gravedad ordinal)
- Análisis de la cartera histórica por año de infracción — herramienta de diagnóstico
  para la gestión de deuda antigua que antes no existía en el SAT
"""

